	bash compile.sh
			echo "binaries built:..............................."
		ls -l BUILD_PFORDELTA_NOTEXT  BUILD_QMXCODING_NOTEXT   BUILD_QMXCODINGSIMD_NOTEXT   BUILD_REPAIR_NOSKIP_NOTEXT   BUILD_REPAIR_SKIP_MOFFAT_NOTEXT   BUILD_REPAIR_SKIP_NOTEXT   BUILD_REPAIR_SKIP_SANDERS_NOTEXT   BUILD_RICE_NOTEXT   BUILD_SIMPLE9_NOTEXT   BUILD_VBYTE_LZMA_NOTEXT  BUILD_VBYTE_NOTEXT 
		ls -l SEARCH_PFORDELTA_NOTEXT SEARCH_QMXCODING_NOTEXT  SEARCH_QMXCODINGSIMD_NOTEXT  SEARCH_REPAIR_NOSKIP_NOTEXT  SEARCH_REPAIR_SKIP_MOFFAT_NOTEXT  SEARCH_REPAIR_SKIP_NOTEXT  SEARCH_REPAIR_SKIP_SANDERS_NOTEXT  SEARCH_RICE_NOTEXT  SEARCH_SIMPLE9_NOTEXT  SEARCH_VBYTE_LZMA_NOTEXT  SEARCH_VBYTE_NOTEXT
		
        sleep 10
