CC = g++
#CFLAGS = -g -pg
CFLAGS = -O3 -Wall -DNDEBUG -g -m64
OBJS = extractor.o extractor77.o utils.o extractorend.o deltacodes.o extractorend2.o LZparser.o LZ77.o utils.o RMQ.o RMQ_succinct.o treelist.o static_bitsequence.o static_bitsequence_brw32.o static_permutation.o static_permutation_mrrr.o static_bitsequence_builder_brw32.o perm.o LZend.nuevo.o LZend.o LZ77_2.o compressor.o
BIN=
LIBCOMPRESSOR = compressorText.a

all: $(OBJS) $(BIN) 
	@echo "[MSG] Done building test"
	ar rc $(LIBCOMPRESSOR) $(OBJS)
	@echo "[AR ] Library contains files: " && ar t $(LIBCOMPRESSOR)

.cpp.o:
	$(CC) $(CFLAGS) -c $<

clean:
	rm -f $(BIN) $(LIBCOMPRESSOR) $(OBJS) test.o core vgcore* *~

.PHONY: sa
sa: 
	make -C sa

testCompressor: test.o $(OBJS) sa
	@echo "[BLD] Building testCompressor (exe): ./testCompressor"
	$(CC) $(CFLAGS) *.o sa/SAu.a -o testCompressor

test:
	@echo "[EXE] check with: ./test <input file text> <input file docbeginings> <output file>"
	@echo "valgrind   ./test /sitio/textos/FT91.TXT /sitio/textos/FT91.TXT.DOCBOUNDARIES outfilename.txt"
	@echo "\n"
	valgrind ./testCompressor textos/FT91.TXT textos/FT91.TXT.DOCBOUNDARIES outfilename.txt
